[package]
name = "client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.11.3"
bevy-inspector-egui = "0.20.0"
bevy_asset_loader = { version = "0.17.0", features = ["2d"] } 
bevy_fly_camera = { git = "https://github.com/zachbateman/bevy_fly_camera.git", rev = "f48cf8db" }
bevy_rapier3d = { version = "0.22.0", features = [ "debug-render-3d", "parallel", "enhanced-determinism" ] }
bevy_mod_raycast = "0.14.1"
bevy_sprite3d = "2.6.0"
rayon = "1.8.0"
wide = "0.7.12"
serde_yaml = "0.9.25"
serde_json = "1.0.107"
serde = {version = "1.0.189", features=["derive"]}
rand = "0.8.5"
message-io = "0.18.0"
shared = { path = "../shared" }

[features]
bevy_dynamic = ["bevy/dynamic_linking"]
default = ["bevy_dynamic"]
