[package]
name = "client"
version = "0.1.0"
edition = "2021"
default-run = "client"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.12.1", features = ["wav"], default-features = false }
serde_yaml = "0.9.27"
serde_json = "1.0.108"
serde = { version = "1.0.193", features = ["derive"] }
rand = "0.8.5"
shared = { path = "../shared", default-features = false }
#bevy_xpbd_3d = "0.3.2"

postcard = { version = "1.0.8", features = ["use-std", "alloc"] }

message-io = { version = "0.18.0", optional = true }
bevy-inspector-egui = { version = "0.21.0", optional = true }
clap = { version = "4.4.11", features = ["derive"] }
noise = "0.8.2"

[features]
inspector = ["dep:bevy-inspector-egui"]
mio-net = ["dep:message-io", "shared/mio-net"]
default = ["mio-net"]
