[package]
name = "client"
version = "0.1.0"
edition = "2021"
default-run = "client"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.12.1"
serde_yaml = "0.9.27"
serde_json = "1.0.108"
serde = { version = "1.0.193", features = ["derive"] }
rand = "0.8.5"
message-io = "0.18.0"
shared = { path = "../shared" }
bevy_xpbd_3d = "0.3.2"
postcard = { version = "1.0.8", features = ["use-std", "alloc"] }

bevy-inspector-egui = { version = "0.21.0", optional = true }

[features]
inspector = ["dep:bevy-inspector-egui"]
default = []
