[package]
name = "server"
version = "0.1.0"
authors = []
edition = "2021"

[dependencies.bevy]
version = "0.10.1"
default-features = false
features = ["serialize", "trace"]

[dependencies]
serde_yaml = "0.9.21"
serde_json = "1.0.96"
serde = {version = "1.0.160", features=["derive"]}

rand = "0.8.5"
message-io = "0.15.1"
#bevy_egui = "0.2.0"
shared = { path = "../shared" }
