[package]
name = "shared"
version = "0.1.0"
authors = []
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies.bevy]
version = "0.10.1"
default-features = false
features = ["serialize"]

[dependencies]
message-io = "0.15.1"
serde_yaml = "0.9.21"
serde_json = "1.0.96"
serde = {version = "1.0.160", features=["derive"]}
once_cell = "1.17.1"
rand = "0.8.5"

# Everything that server has, we also have
bevy_ecs = "0.10.1"
bevy_app = "0.10.1"
bevy_log = "0.10.1"
bevy_core = "0.10.1"
bevy_time = "0.10.1"
bevy_transform = "0.10.1"
bevy_hierarchy = "0.10.1"
bevy_diagnostic = "0.10.1"
