[package]
name = "shared"
version = "0.1.0"
authors = []
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies.bevy]
version = "0.10.1"
default-features = false
features = ["serialize", "trace"]

[dependencies]
message-io = "0.15.1"
serde_yaml = "0.9.21"
serde_json = "1.0.96"
serde = {version = "1.0.160", features=["derive"]}
once_cell = "1.17.1"
rand = "0.8.5"
